spring:
  application:
    name: insight-vault
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME:insightvault}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    validate-migration-naming: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
  ai:
    vectorstore:
      elasticsearch:
        dimensions: 1024
        initialize-schema: true
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
security:
  jwt:
    key:
      private: ${JWT_PRIVATE_KEY_PATH}
      public: ${JWT_PUBLIC_KEY_PATH}
    token:
      access:
        expiry-in-seconds: 3600
      refresh:
        expiry-in-seconds: 10800
    roles-claim-name: roles
minio:
  inner-endpoint: ${MINIO_INNER_ENDPOINT:http://localhost:9000}
  outer-endpoint: ${MINIO_OUTER_ENDPOINT:${minio.inner-endpoint}}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:docs}
