spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:insightvault}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://elasticsearch:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
  ai:
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
security:
  jwt:
    key:
      private: file:/app/.secrets/keys/app.key
      public: file:/app/.secrets/keys/app.pub
minio:
  inner-endpoint: ${MINIO_INNER_ENDPOINT:http://minio:9000}
  outer-endpoint: ${MINIO_OUTER_ENDPOINT:${minio.inner-endpoint}}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:docs}
