create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    email      varchar(255) not null
        constraint idx_email
            unique,
    name       varchar(100),
    password   varchar(255) not null,
    role       varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    username   varchar(50)  not null
        constraint idx_username
            unique
);
