create table insights
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    answer     oid          not null,
    question   varchar(500) not null,
    record_id  varchar(255),
    user_id    bigint       not null
        constraint fk_user_id
            references users
);
